CREATE TABLE Privilegesi(
    id_Privilege VARCHAR(20) NOT NULL PRIMARY KEY,
    Type_Privilege VARCHAR(255) NOT NULL,
    Id_Pressing VARCHAR(255) UNIQUE NOT NULL,
    Id_User VARCHAR (255) NOT NULL 
);