CREATE TABLE Promo (
    Id_promo VARCHAR(255) NOT NULL PRIMARY KEY,
    Id_Offre VARCHAR(255) NOT NULL,
    Id_Service VARCHAR(255) NOT NULL,
    Id_Type_service VARCHAR(255) NOT NULL,
    Id_Annonce VARCHAR(255) NOT NULL,
    Id_Type_linge VARCHAR(255) UNIQUE NOT NULL,
    Id_Pressing VARCHAR(20) NOT NULL
);