CREATE TABLE Services (
    Id_Service VARCHAR(255) NOT NULL PRIMARY KEY,
    Id_Pressing VARCHAR(255) NOT NULL,
    Id_Type_linge VARCHAR(255) NOT NULL,
    Id_Type_service VARCHAR(255) UNIQUE NOT NULL
);